# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Creates Signs and Pushes a NuGet from a Nuspec file called template.nuspec located in the root of workspace"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '6.x'
          
      - name: Create NuGet Package
        run: |
         nuget pack template.nuspec -NoDefaultExcludes -NonInteractive
         
      - name: Find created nuget
        id: findcreatednuget
        run: echo "nugetPackageName=$(dir *.nupkg /b))" >> $env:GITHUB_OUTPUT
        shell: cmd
        
      - name: Download Encrypted Signature File
        id: downloadSignatureFile
        run: |
          text_file = open("encryptedSkylineSignature", "w")
          #write string to file
          text_file.write('${{ secrets.SKYLINEPFX }}')
          text_file.close()
        shell: python
        
      - name: Decrypt Signature File
        id: decryptSignatureFile
        run: certutil -decode encryptedSkylineSignature Skyline.pfx
        shell: cmd

      - name: Sign NuGet Package
        run: |
         nuget sign "${{ steps.findcreatednuget.outputs.nugetPackageName }}" -NonInteractive -CertificatePath "Skyline.pfx" -Timestamper "http://timestamp.comodoca.com/rfc3161" -CertificatePassword ${{ secrets.SKYLINEPFXPASSWORD }}
